apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
data:
  config.yaml: |
{{ .Files.Get "files/apisix-config.yaml" | indent 4 }}
  apisix.yaml: |
{{ .Files.Get "files/apisix.yaml" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix-gateway
spec:
  replicas: 1
  selector:
    matchLabels: { app: apisix-gateway }
  template:
    metadata:
      labels: { app: apisix-gateway }
    spec:
      containers:
        - name: apisix
          image: "{{ .Values.services.apisix.image }}"
          ports:
            - containerPort: {{ .Values.services.apisix.port }}
          volumeMounts:
            - name: cfg
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
            - name: cfg
              mountPath: /usr/local/apisix/conf/apisix.yaml
              subPath: apisix.yaml
      volumes:
        - name: cfg
          configMap:
            name: apisix-config
---
apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
spec:
  type: NodePort
  selector: { app: apisix-gateway }
  ports:
    - port: {{ .Values.services.apisix.port }}
      targetPort: {{ .Values.services.apisix.port }}
      nodePort: {{ .Values.services.apisix.nodePort }}
