# Multi-stage GraalVM native build for mohana-tpp.
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 AS build
USER root
WORKDIR /code
COPY --chown=quarkus:quarkus . /code
RUN ./mvnw -q -pl common,mohana-tpp -am -Pnative -DskipTests package

FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /work
COPY --from=build /code/mohana-tpp/target/*-runner /work/application
RUN chmod 775 /work/application
EXPOSE 8080
USER 1001
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
